name: GitHub Profile Stats

on:
  schedule:
    # run everyday at 12:00 UTC
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  Collect-GitHub-Stats:
    runs-on: ubuntu-latest
    concurrency:
      group: stats-concurrency
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3

      - name: profile-stats
        uses: LukeHagar/stats-action@main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - uses: stefanzweifel/git-auto-commit-action@v5
